/*
LOG_LEVEL
   LOG_LEVEL_DISABLE
   LOG_LEVEL_ERROR
   LOG_LEVEL_WARNING
   LOG_LEVEL_INFO
   LOG_LEVEL_DEBUG
   LOG_LEVEL_VERBOSE

LOG_TIME
   LOG_TIME_NONE
   LOG_TIME_MICROS
   LOG_TIME_MILLIS
   LOG_TIME_HHMMSSMS
   LOG_TIME_HHHHMMSSMS

LOG_FILTER
   LOG_FILTER_NONE
   LOG_FILTER_EXCLUDE
   LOG_FILTER_INCLUDE

LOG_COLORS
   LOG_COLORS_DISABLE
   LOG_COLORS_ENABLE

LOG_TAG_TYPE
   LOG_TAG_SHORT
   LOG_TAG_LONG

LOG_PRINT_TYPE
   LOG_TYPE_PRINTF
   LOG_TYPE_STD_FORMAT
*/

#define LOG_LEVEL LOG_LEVEL_VERBOSE

#define LOG_TIME LOG_TIME_DISABLE

#define LOG_FILTER LOG_FILTER_DISABLE

#define LOG_FILTER_LIST {""}

#define LOG_COLORS LOG_COLORS_ENABLE

#define LOG_TAG_TYPE LOG_TAG_LONG

#define LOG_PRINT_TYPE LOG_TYPE_PRINTF

#define LOG_OUTPUT Serial

#include <Logger.h>