// #pragma once

/*
LOG_LEVEL
   LOG_LEVEL_DISABLE
   LOG_LEVEL_ERROR
   LOG_LEVEL_WARNING
   LOG_LEVEL_INFO
   LOG_LEVEL_DEBUG
   LOG_LEVEL_VERBOSE

LOG_LEVEL_TEXT_FORMAT
   LOG_LEVEL_TEXT_FORMAT_SINGLE
   LOG_LEVEL_TEXT_FORMAT_SHORT
   LOG_LEVEL_TEXT_FORMAT_FULL

LOG_TIME
   LOG_TIME_DISABLE
   LOG_TIME_MICROS
   LOG_TIME_MILLIS
   LOG_TIME_HHMMSSMS
   LOG_TIME_HHHHMMSSMS

LOG_FILENAME
   LOG_FILENAME_DISABLE
   LOG_FILENAME_ENABLE

LOG_COLORS
   LOG_COLORS_DISABLE
   LOG_COLORS_ENABLE

LOG_FILTER
   LOG_FILTER_NONE
   LOG_FILTER_EXCLUDE
   LOG_FILTER_INCLUDE

LOG_PRINT_TYPE
   LOG_PRINT_TYPE_PRINTF
   LOG_PRINT_TYPE_STD_FORMAT
   LOG_PRINT_TYPE_FMT_FORMAT
*/

#define LOG_LEVEL LOG_LEVEL_VERBOSE

#define LOG_LEVEL_TEXT_FORMAT LOG_LEVEL_TEXT_FORMAT_SINGLE

#define LOG_TIME LOG_TIME_HHMMSSMS

#define LOG_FILENAME LOG_FILENAME_ENABLE

#define LOG_COLORS LOG_COLORS_ENABLE

#define LOG_FILTER LOG_FILTER_EXCLUDE

#define LOG_FILTER_LIST {"War"}

#define LOG_PRINT_TYPE LOG_PRINT_TYPE_FMT_FORMAT

#define LOG_OUTPUT Serial

#include <Logger.h>