/*
   LOG_LEVEL_NONE,
   LOG_LEVEL_ERROR,
   LOG_LEVEL_WARNING,
   LOG_LEVEL_INFO,
   LOG_LEVEL_DEBUG
   LOG_LEVEL_VERBOSE,
*/

#define LOG_LEVEL LOG_LEVEL_VERBOSE

#define LOG_FILTER LOG_FILTER_EXCLUDE

#define LOG_FILTER_LIST ""

#define LOG_USE_TIME 0

#define LOG_USE_TAG_SHORT 0

#define LOG_USE_COLORS 1

#define LOG_OUTPUT Serial

#include <logger.h>